export const departamentos = [
  "Amazonas", "Antioquia", "Arauca", "Atlántico", "Bolívar", "Boyacá",
  "Caldas", "Caquetá", "Casanare", "Cauca", "Cesar", "Chocó", "Córdoba",
  "Cundinamarca", "Guainía", "Guaviare", "Huila", "La Guajira", "Magdalena",
  "Meta", "Nariño", "Norte de Santander", "Putumayo", "Quindío", "Risaralda",
  "San Andrés y Providencia", "Santander", "Sucre", "Tolima",
  "Valle del Cauca", "Vaupés", "Vichada", "Bogotá D.C.",
];

export const ciudadesPorDepartamento: Record<string, string[]> = {
  "Bogotá D.C.": ["Bogotá"],
  Antioquia: ["Medellín", "Bello", "Itagüí", "Envigado", "Rionegro", "Apartadó", "Turbo"],
  "Valle del Cauca": ["Cali", "Buenaventura", "Palmira", "Tuluá", "Buga", "Cartago"],
  Atlántico: ["Barranquilla", "Soledad", "Malambo", "Sabanalarga", "Baranoa"],
  Cundinamarca: ["Soacha", "Facatativá", "Zipaquirá", "Chía", "Mosquera", "Madrid", "Fusagasugá"],
  Santander: ["Bucaramanga", "Floridablanca", "Girón", "Piedecuesta", "Barrancabermeja"],
  Bolívar: ["Cartagena", "Magangué", "El Carmen de Bolívar", "Turbaco"],
  Nariño: ["Pasto", "Tumaco", "Ipiales", "Túquerres"],
  Córdoba: ["Montería", "Cereté", "Lorica", "Sahagún", "Montelíbano"],
  Tolima: ["Ibagué", "Espinal", "Melgar", "Flandes", "Honda"],
  Boyacá: ["Tunja", "Duitama", "Sogamoso", "Chiquinquirá"],
  Caldas: ["Manizales", "La Dorada", "Riosucio", "Salamina"],
  Risaralda: ["Pereira", "Dosquebradas", "Santa Rosa de Cabal"],
  Quindío: ["Armenia", "Calarcá", "Montenegro", "Quimbaya"],
  Huila: ["Neiva", "Pitalito", "Garzón", "La Plata"],
  Meta: ["Villavicencio", "Acacías", "Granada", "Puerto López"],
  Cesar: ["Valledupar", "Aguachica", "Bosconia", "El Copey"],
  "La Guajira": ["Riohacha", "Maicao", "Uribia", "Manaure"],
  Magdalena: ["Santa Marta", "Ciénaga", "Fundación", "El Banco"],
  Cauca: ["Popayán", "Santander de Quilichao", "Puerto Tejada"],
  "Norte de Santander": ["Cúcuta", "Ocaña", "Pamplona", "Villa del Rosario"],
  Sucre: ["Sincelejo", "Corozal", "Sampués", "San Marcos"],
  Chocó: ["Quibdó", "Istmina", "Tumaco"],
  Arauca: ["Arauca", "Saravena", "Tame", "Fortul"],
  Casanare: ["Yopal", "Aguazul", "Paz de Ariporo", "Villanueva"],
  Putumayo: ["Mocoa", "Puerto Asís", "Orito", "Sibundoy"],
  Caquetá: ["Florencia", "San Vicente del Caguán", "El Doncello"],
  Amazonas: ["Leticia", "Puerto Nariño"],
  Guainía: ["Inírida"],
  Guaviare: ["San José del Guaviare", "El Retorno"],
  Vaupés: ["Mitú"],
  Vichada: ["Puerto Carreño", "La Primavera"],
  "San Andrés y Providencia": ["San Andrés", "Providencia"],
};

export const bancos = [
  "Bancolombia",
  "Banco de Bogotá",
  "Davivienda",
  "BBVA Colombia",
  "Banco Popular",
  "Banco de Occidente",
  "Banco AV Villas",
  "Banco Caja Social",
  "Nequi",
  "Daviplata",
  "Bancamía",
  "Banco Agrario",
  "Banco W",
  "Banco Falabella",
  "Banco Finandina",
  "Banco GNB Sudameris",
  "Banco Pichincha",
  "Itaú Colombia",
  "Scotiabank Colpatria",
];
